### ISSUE TITLE
extra_parameters  not passing correctly for vRA version  7.X

### ISSUE THREAD

**Issue by thomasdbaker** [chef-partners/kitchen-vra#20]
Resulting in the following error:

Error:  Failed to complete #create action:  [unable to submit request:  the data specified within the request is invalid., Composition Exception.

**Comment by jjasghar** [comment]
Yep, we are working on this. It's from an upstream issue. :(

**Comment by jjasghar** [comment]
Basiclly we need to figure out how to add extra-params to this: https://github.com/chef-partners/vmware-vra-gem/blob/master/lib/vra/catalog_request.rb#L79-L85 

Please reopen this in the vmware-vra-gem, this isn't specific to kitchen-vra.
