### ISSUE TITLE
Feature Query: Support for Capture Snapshot & Restore Snapshot

### ISSUE THREAD

**Issue by aytch** [chef-partners/kitchen-vra#27]
### Platform Details

* Version of vRA: 7.2.0
* Version of ESXi: 6.5

### Scenario:
It would be very useful to be able to use the kitchen-vra gem to capture snapshots and restore snapshots to a test-kitchen instance.

**Comment by jjasghar** [comment]
First question, can this be done via the VMware vRA API?

This seems pretty challenging, can you write out what you think the workflow would be like? I don't use snapshots with vRA and I think I get the use case but a deeper explanation would be useful.

**Comment by aytch** [comment]
It doesn't look it can be done with the vRA API, I'm afraid - it appears that that functionality relies within the vSphere API. I was hopeful it could be done since the snapshot functionality does appears in the VRA UI.

After some further consideration, I'll close this feature request, as it would greatly increase the complexity of kitchen-vra in a way that isn't beneficial. Thank you for the consideration, though!
