### ISSUE TITLE
server_ready_retries timeout growth is awkward for our use case

### ISSUE THREAD

**Issue by theballdredge** [chef-partners/kitchen-vra#8]
when creating machines using vRA our system has some post processing that takes a few minutes to complete, and often runs into larger timeout values.  specifically, the timeout frequently runs past the 256s timeout and often triggers the 512s delay.  

it would be really nice if one could set a base delay before delay scaling kicks in.

**Comment by adamleff** [comment]
What about changing the delay growth to just add 5 secs each time rather than doubling? That gets you closer to what you're looking for, but also keeps the relative simplicity of the current delay+retry logic.

**Comment by theballdredge** [comment]
definitely closer.  the delay at the point the machine is ready is going to be in the 80-90s range, vice 512.

**Comment by theballdredge** [comment]
might be nice to be able to specify the duration too, time permitting.

**Comment by adamleff** [comment]
The main reason it's in here is I've seen the vRA API lose its mind if it's used too much, requiring a restart of the software.

I think the right call here is to add 5 minutes each time up to a max of a 30-sec delay. I think that's pretty reasonable.

**Comment by theballdredge** [comment]
capping the delay sounds like an excellent compromise.

aside - which versions of vRA have you seen misbehaving?

**Comment by adamleff** [comment]
PR #10 opened for this - please follow that PR for additional updates.

I believe it was 6.2, or 6.2.1, that I was seeing the API scalability issues.

**Comment by adamleff** [comment]
kitchen-vra v1.3.0 has been released with this change - thanks again for raising your concerns to us.
